### ISSUE TITLE
Add dependabot

### ISSUE THREAD

**Issue by ldellisola** [Mamis-Solidarias/Users#22]
This config file should check for nuget dependencies
```
version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 25
```
